obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.5

#---(in meters)---
footprint: [ [0.325, 0.25], [-0.325, 0.25], [-0.325, -0.25], [0.325, -0.25] ]

transform_tolerance: 5.0
map_type: costmap

observation_sources: laser_scan_sensor other_robot_info
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true, expected_update_rate: 0.2}

